import MyProfilePic from './components/MyProfilePic'
import Navbar from './components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Rukshar's Blog",
  description: 'Generated by Rukshar',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={'dark:bg-slate-800'}>
        <Navbar/>
        <MyProfilePic/>
        {children}
      </body>
    </html>
  )
}
